### PR TITLE
WIP - 20 Allow AC Reveal in Player Window

### PR DESCRIPTION
**Pull request by chrisbloom7**
ezgif com-optimize 2

Looking for early feedback. Is this heading towards what was envisioned?

### CODE REVIEW

**Comment by cynicaloptimist** [comment]
I don't like how this approach clutters the UI, but the functionality seems good. I think if you put this behind a Player View option it would be a good start, but I'd like to see a more subtle impact on the UI for this.

**Comment by chrisbloom7** [comment]
@cynicaloptimist open to suggestions on what a more subtle approach may look like. I design like an engineer :)

**Comment by cynicaloptimist** [comment]
It would be best for this button to be a command (as well as the original hide/reveal combatant button).

FYI, I'm planning to do a big rework on how commands are displayed. The new design might wind up with them appearing directly on the selected or hovered combatant, instead of on the sidebar.

**Comment by chrisbloom7** [comment]
Sounds like it might be best for me to wait until your command refactor is complete, then I can readdress this. Will leave open for now as a reminder.

**Pull request closed without merging**
